version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: ../nginx/nginx.Dockerfile
    ports:
      - "80:80"  # Required for Let's Encrypt challenge
      - "443:443"
    volumes:
      - letsencrypt:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - mynetwork
    env_file: ".env"
    restart: always

networks:
  nginx_network:
    driver: bridge 